### PR TITLE
Lei reset last modified date

### PR DESCRIPTION
**Pull request by leiwang008**
I have written ResetCommitDate.java and modified safs.build.xml to use it instead of ResetCommitDate.vbs.
I remove ResetCommitDate.vbs.
Please review my modification, thanks.

### CODE REVIEW

**Comment by sascanagl** [comment]
The changes look fine.  I'll let Lei or Tao perform the Merge once they are ready.

A reminder, one of the files modified is the bootstrap.build.xml file.  This requires manual intervention for users to place the new version in the proper location in their build systems.  For Jenkins that has been in the parent directory of the build job using it.

I note that ResetCommitDate.java is compiled in-place before use.  So I assume the user has no manual intervention requirements for the placement of this new file.

**Comment by leiwang008** [comment]
Many thanks for the reminder :-)
I will replace bootstrap.build.xml in Jenkins build machine.
For ResetCommitDate.java, I think it doesn't need manual intervention, our ant script will download it and compile and run it automatically. I will merge this branch and test to make sure of it.

**Comment by leiwang008** [comment]
You are right, I still need to modify bootstrap.build.xml to get the ResetCommitDate.java. I will modify that directly in the master branch.

**Comment by leiwang008** [comment]
I have modified the 4 jobs on our Jenkins server by adding a step to copy the "updated bootstrap.build.xml" to the Jenkins root so that next build will use it. And we don't need any manual intervention anymore.

**Pull request merged**
